
networks:
  crawler_net:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:8.7.0
    configs:
      - source: elasticsearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - ./volumes/es_data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node  
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
    networks:
      - crawler_net  

  master:
    build: ./master
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
    networks:
      - crawler_net

  redis:
    image: redislabs/redisearch:latest
    configs:
      - source: redis_config
        target: /usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes --loadmodule /usr/lib/redis/modules/redisearch.so    
    volumes:
      - ./volumes/redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
    ports:
      - "6379:6379"  
    networks:
      - crawler_net  


  crawler:
    build: ./crawler
    environment:
      - REDIS_HOST=masternodee 
      - MASTER_HOST=	masternodee 
    volumes:
      - ./crawler/config:/app/config
    networks:
      - crawler_net  

  indexer:
    build: ./indexer
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./indexer/mappings:/app/mappings
    networks:
      - crawler_net

  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy




configs:
  elasticsearch_config:
    file: ./configs/elasticsearch.yml
  redis_config:
    file: ./configs/redis.conf