
networks:
  crawler_net:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:8.7.0
    configs:
      - source: elasticsearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - ./volumes/es_data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node  
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
    networks:
      - crawler_net  


  master:
    build: ./master
    networks:
      - crawler_net


  crawler_1:
    build: .
    environment:
      - CRAWLER_ID=crawler-1
    restart: always

  crawler_2:
    build: .
    environment:
      - CRAWLER_ID=crawler-2
    restart: always


  indexer:
    build: ./indexer
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./indexer/mappings:/app/mappings
    networks:
      - crawler_net



configs:
  elasticsearch_config:
    file: ./configs/elasticsearch.yml
  redis_config:
    file: ./configs/redis.conf